package com.palarz.mike.songsearch;

import com.google.gson.annotations.SerializedName;

/**
 * A class that was created that corresponds to the response that is generated by the Spotify
 * Web API when the access token is successfully generated. This class is primarily used in
 * order to parse the response and extract the access token.
 *
 * For more information, see the Spotify Authorization guide for the Client Credentials flow:
 *
 * https://beta.developer.spotify.com/documentation/general/guides/authorization-guide/#client-credentials-flow
 *
 */

class TokenResponse {

    @SerializedName("access_token")
    String mAccessToken;

    @SerializedName("token_type")
    String mTokenType;

    @SerializedName("expires_in")
    int mExpiration;

    public TokenResponse() {
        this.mAccessToken = "";
        this.mTokenType = "";
        this.mExpiration = 0;
    }

    public TokenResponse(String accessToken, String tokenType, int expiration) {
        this.mAccessToken = accessToken;
        this.mTokenType = tokenType;
        this.mExpiration = expiration;
    }


    public String getAccessToken() {
        return mAccessToken;
    }

    public String getTokenType() {
        return mTokenType;
    }

    public int getExpiration() {
        return mExpiration;
    }

}
